### ISSUE TITLE
Log configured URLs when one is not found

### ISSUE THREAD

**Issue by pkalbrun-goeuro** [PawelAdamski/HttpClientMock#6]
Would be nice to have a list of set URLs when executed URL is not found in the configuration. It will speed up debugging. Please and thank you! :)

**Comment by PawelAdamski** [comment]
Done. 
Now if no rule matches HttpClientMock will print debug information (like bellow). In case you would like to turn on debugging for every request you must write `httpClientMock.debugOn();`
This changes are available since version 1.0.3
```
Request: GET http://localhost/login
Rule 1:
	MATCHES		EXPECTED
	true		HTTP method is GET
	true		schema is "http"
	true		host is "localhost"
	true		path is "/login"
	true		port is empty
Rule 2:
	MATCHES		EXPECTED
	true		HTTP method is GET
	true		schema is "http"
	true		host is "localhost"
	false		path is "/user"
	true		port is empty
```

@pkalbrun-goeuro please share your feedback about this feature.
